version: '3'

services:
  django:
    build: ./
    environment:
      - DATABASE_URL=postgresql://django:password@postgres:5432/django
    command: sh -c "gunicorn --bind 0.0.0.0:8000 notes_store.wsgi"
    depends_on:
      - postgres
    volumes:
      - ./:/notes_store
      - ./static:/notes_store/static
    expose:
      - 8000

  postgres:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django

  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - ./static:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pg_data: