export const SET_INIT = 'SET_INIT'
export const SET_IS_FORM_UPLOADING = 'SET_IS_FORM_UPLOADING'
export const SET_CSRF = 'SET_CSRF'
export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'
